task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 # your dataset classes    # laptq
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /    # laptq
    ann_file: /home/lap_awlv/laptq-nedo-fed/outputs/helper--convert--ultralytics-txt--to--coco/train_d1_90k.json    # laptq
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 32    # laptq
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /    # laptq
    ann_file: /home/lap_awlv/laptq-nedo-fed/outputs/helper--convert--ultralytics-txt--to--coco/valid_d1_90k.json    # laptq
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 32    # laptq
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
