print_freq: 1
output_dir: '/home/lap_awlv/laptq-nedo-fed/runs/data--c1/dfine_hgnetv2_s/logs'
checkpoint_freq: 30


sync_bn: True
find_unused_parameters: False


use_amp: False
scaler:
  type: GradScaler
  enabled: True


use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000

use_wandb: False
project_name: D-FINE # for wandb
exp_name: baseline # wandb experiment name
